---
language: java
dist: jammy

jdk:
- openjdk11

notifications:
  email: true

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

stages:
  - name: Build-Test
  - name: Semantic-Release
    if: branch = master AND type = push AND fork = false
  - name: Publish-Release
    if: tag IS present

before_install:
  # Need to install this key to avoid GPG errors during `apt update`
  # because the perforce key pre-installed in the travis build image expired on 8/14/2023.
  # Reference: https://www.perforce.com/manuals/p4sag/Content/P4SAG/install.linux.packages.install.html
  - wget -qO - https://package.perforce.com/perforce.pubkey | sudo apt-key add -
  - sudo apt-get update
  - echo -e "machine github.ibm.com\n  login $GITHUB_ACCESS_TOKEN" > ~/.netrc

jobs:
  include:
    - stage: Build-Test
      jdk: openjdk11
      install: true
      script:
        - build/setMavenVersion.sh
        - mvn verify -fae -DskipITs $MVN_ARGS

    - jdk: openjdk17
      install: true
      script:
        - mvn verify -fae -DskipITs $MVN_ARGS

    - stage: Semantic-Release
      install:
        - nvm install 18
        - node --version
        - npm --version
        - npm install
        - pip install --user bump2version
      script:
        - npm run semantic-release
      after_success:
        - echo "Semantic release has successfully created a new tagged-release"

    - stage: Publish-Release
      jdk: openjdk11
      name: Publish-Javadoc
      install: true
      script:
        - build/setMavenVersion.sh
        - mvn clean javadoc:aggregate $MVN_ARGS
        - build/publishJavadoc.sh
      after_success:
        - echo "Javadocs successfully published to gh-pages!"

    - jdk: openjdk11
      name: Publish-To-Maven-Central
      install: true
      script:
        - build/setupSigning.sh
        - build/setMavenVersion.sh
        - mvn deploy $MVN_ARGS -DskipTests -P central
      after_success:
        - echo "Maven artifacts successfully published to Maven Central!"

